/* AUTHENTICATION */

export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";

export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_REGISTER_FAILURE = "AUTH_REGISTER_FAILURE";

export const AUTH_LOGOUT= "AUTH_LOGOUT";

/*ARTICLE*/
export const ARTICLE_POST = "ARTICLE_POST";
export const ARTICLE_POST_SUCCESS = "ARTICLE_POST_SUCCESS";
export const ARTICLE_POST_FAILURE = "ARTICLE_POST_FAILURE";

export const ARTICLE_LIST = "ARTICLE_LIST";
export const ARTICLE_LIST_SUCCESS = "ARTICLE_LIST_SUCCESS";
export const ARTICLE_LIST_FAILURE = "ARTICLE_LIST_FAILURE";

export const ARTICLE_EDIT = "ARTICLE_EDIT";
export const ARTICLE_EDIT_SUCCESS = "ARTICLE_EDIT_SUCCESS";
export const ARTICLE_EDIT_FAILURE = "ARTICLE_EDIT_FAILURE";

export const ARTICLE_REMOVE = "ARTICLE_REMOVE";
export const ARTICLE_REMOVE_SUCCESS = "ARTICLE_REMOVE_SUCCESS";
export const ARTICLE_REMOVE_FAILURE = "ARTICLE_REMOVE_FAILURE";

export const ARTICLE_PUBLISH = "ARTICLE_PUBLISH";
export const ARTICLE_PUBLISH_SUCCESS = "ARTICLE_PUBLISH_SUCCESS";
export const ARTICLE_PUBLISH_FAILURE = "ARTICLE_PUBLISH_FAILURE";

export const HOME_LIST = "HOME_LIST";
export const HOME_LIST_SUCCESS = "HOME_LIST_SUCCESS";
export const HOME_LIST_FAILURE = "HOME_LIST_FAILURE";

export const SELECTED_ARTICLE = "SELECT_ARTICLE";